### ISSUE TITLE
Using external datasets

### ISSUE THREAD

**Issue by tprelog** [ix-plugin-hub/iocage-plugin-index#120]
Are there any plans for adding the ability, so we can mount an external dataset before the installation of a plugin?

I know this can be done after the fact, but it's not always so straight forward. For example, if there is configuration created during the install, then mounting an external dataset becomes a multi-step process at best

1. Enter jail
2. Disable and stop what ever service the plugin provides
3. Move existing configuration out of the way (to create an empty mount point)
4. Stop the jail and add the mount point using the TrueNAS UI
5. Start and enter the jail
6. Move the configuration (from step 3) back to the correct location
7. Finally, enable and start what ever service the plugin provides

It would be most excellent if we set mount points first, so a plugin can have extra datasets already mounted _during the installation_.

![image](https://user-images.githubusercontent.com/35702532/96475986-adcc1600-1202-11eb-8783-9bfb61a32e23.png)

IMO, this addition could be a game changer for iocage plugins to be successful. Personally, I'm already looking hard at switching over to Scale when its released next year. For me, it literally boils down to the fact that I can define a mount point in a `docker-compose.yaml` and have whatever service spin-up with external configuration already in place.

**Comment by kmoore134** [comment]
At the moment we hadn't planned to re-do that for CORE/Enterprise, however there is obviously room to do it on SCALE, since we're actively in development for its Plugin ecosystem. This would be a great suggestion ticket on jira.ixsystems.com for us to review though, to get it on our radar.

**Comment by jsegaert** [comment]
This was logged as a feature request with iocage project:  iocage/iocage#1191

The idea would be to add such functionality to the plugin's manifest, to mount storage at plugin creation.
