### ISSUE TITLE
Wrong release version on 12.2-RELEASE branch?

### ISSUE THREAD

**Issue by fmunteanu** [ix-plugin-hub/iocage-plugin-index#135]
Can you please let me know why the release version is listed as `12.1-RELEASE` on the new `12.2-RELEASE` branch, should this be updated?
https://github.com/ix-plugin-hub/iocage-plugin-index/blob/12.2-RELEASE/nzbget.json#L4

Let me know if you need me to create a PR.

**Comment by tprelog** [comment]
Looks like it's fixed now - this issue can be closed
