### ISSUE TITLE
jexec: execvp: /root/post_install.sh: Permission denied

### ISSUE THREAD

**Issue by zorglube** [ix-plugin-hub/iocage-plugin-index#163]
Hello, 

I'm trying to package the project [MovieNight](https://github.com/zorchenhimer/MovieNight) as an TrueNAS Plugin. I know it quite well, I had built it many times, and I run an instance on my TrueNAS. 
I had started the job to make the plugin deployment files and scripts. 
I had submitted an Pull Request during the steps. 
I'm now testing the `iocage` plugin deployment and I'm stuck in an issue. When I run `iocage fetch --plugins --git_repository https://github.com/zorglube/iocage-plugin-index.git dhcp="on" --branch master --update` I have this error `jexec: execvp: /root/post_install.sh: Permission denied` AND i don't understand why `post_install.sh` can't be run AND how to fix that. 

If anyone can help, I'll be glad you read your advises. 

Zorglube

**Comment by tprelog** [comment]
Please see https://github.com/ix-plugin-hub/iocage-plugin-index/pull/162#issuecomment-778873255
