### ISSUE TITLE
Movie Night don't appear into TrueNAS plugin list.

### ISSUE THREAD

**Issue by zorglube** [ix-plugin-hub/iocage-plugin-index#171]
Few hours ago my [PR](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/162) to add `Movie Night` the plugin index was accepted. 
Since I tried few refresh BUT unfortunately I can't see is into the plugin list. 

![2021-02-23 00 54 22 - 37279d932824](https://user-images.githubusercontent.com/630192/108785554-f0677b80-7571-11eb-9b2e-b6dc73099349.png)

Definitely I'm missing something but I don't see what... Any help will be gratefully accepted. 

BR, 
Zorglube

**Comment by tprelog** [comment]
remember, it's a 2 step process @zorglube  -- step 1, merge to master is complete

but it still won't show up in TrueNAS until the master branch get synced to the 12.2-RELEASE branch

**Comment by zorglube** [comment]
It's the first thing I though, and I looked the list of plugin in my server and the list into `INDEX` from the branches `master`, `12.2-RESELASE`, `12.1-RELLEASE`, etc...  And it seems that the list I can see in my server is the list from `master`. If I didn't made mistake.
