### ISSUE TITLE
Error while installing Piwigo

### ISSUE THREAD

**Issue by alexwcrafter** [ix-plugin-hub/iocage-plugin-index#196]
I was installing Piwigo through my TrueNAS and I always get stuck at the Error "Cannot connect to server" ![Screenshot](https://i.imgur.com/5jHKRRd.png)

I don't know if that's a Database Error or something different but that was happening to me the whole time.
I even tried to add the MariaDB port but that didn't help either.

>Current FreeNAS/TrueNAS version: TrueNAS-12.0-STABLE

**Comment by fulder** [comment]
@alexwcrafter I found this line in the plugin repo (https://github.com/AfroUSApl/iocage-plugin-piwigo) README:

> Piwigo first installation page will set Host: as localhost, usually this needs to be changed to 127.0.0.1

Changing it to the localhost address seems to work fine and I got past this error.

**Comment by alexwcrafter** [comment]
This time it says the connection was made but the database wasn't found.

**Comment by fulder** [comment]
Oh sorry, your database on your picture seems a bit incorrect as well (missed that). I think it should be `piwigodb` not `piwigo`. Maybe that will work better? :)

**Comment by alexwcrafter** [comment]
Yup. That worked perfectly. Thank you!
