### ISSUE TITLE
Deluge plugin install fails

### ISSUE THREAD

**Issue by InfamousUser** [ix-plugin-hub/iocage-plugin-index#206]
Trying to install the Deluge plugin on TrueNAS 12.0-U2 fails with an error:
"Jail: Deluge_new has a missing configuration, please check that the dataset is mounted."

The dataset has been selected in jails menu and there is another jail already running on it.

**Comment by Richardgriff** [comment]
HI,

I am trying to install the Deluge Plugin on TrueNas 12.0-U3 and it also fails on install. My message is slightly diffrent.

"Error: deluge had a failure Exception: RuntimeError Message: pkg error: - py37-pip :,py37-pillow :,py37-libtorrent-rasterbar : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed"

Can anyone help.

Thanks

**Comment by fulder** [comment]
@Richardgriff the issue you're mentioning should now be solved, could you try refreshing your plugin index and installing the plugin once again? :)

**Comment by GAJony** [comment]
This Also happened to me, but on TrueNAS 12.0 U8.1

RuntimeError Message: pkg error: - py38-pip :,py38-pillow :,py38-libtorrent-rasterbar : Refusing to fetch artifact and run post_install.sh!

Is there a way to get around this? or is there a fix for this i can apply?

**Comment by limitlesskeil** [comment]
This also appears to be happening on 13.1 using PY39-libtorrent-rasterbar. 

![image](https://user-images.githubusercontent.com/83790577/187661573-fb59a743-f2aa-4814-b7be-2e9632b2732c.png)

**Comment by ForsakenRei** [comment]
I can comfirm the issue was not solved in TureNAS Core 13.1

**Comment by lawrencesystems** [comment]
TrueNAS-13.0-U2 has the same issue.

**Comment by ccanaria** [comment]
> 

ditto

**Comment by weischin** [comment]
Confirm py39-libtorrent-rasterbar pkg error. Unable to install from the interface. Had to do manual using `pkg install deluge`

**Comment by Pyrrotech** [comment]
Still an issue in  
TrueNAS-13.0-U2. Could not install Deluge today for same error

**Comment by geekhousecalls** [comment]
> @Richardgriff the issue you're mentioning should now be solved, could you try refreshing your plugin index and installing the plugin once again? :)

Still an issue in TrueNAS-12.0-U8.1

**Comment by AlexanderFeyaerts** [comment]
Still broken.

**Comment by agorgl** [comment]
Same here

**Comment by sonicaj** [comment]
Okay 13.1-RELEASE has been updated from master so we should be good as long as the fixes are in master.
