### ISSUE TITLE
deluge-pip wont fetch python3.7 packages [Possible Fix]

### ISSUE THREAD

**Issue by Richardgriff** [ix-plugin-hub/iocage-plugin-index#225]
Hi, I had troble installing deluge-pip from the plugin index.

When installing as follows

```
fetch https://raw.githubusercontent.com/ix-plugin-hub/iocage-plugin-index/master/deluge-pip.json
iocage fetch -P deluge-pip.json -n deluge nat=1
```

[deluge-pip_fail.txt](https://github.com/ix-plugin-hub/iocage-plugin-index/files/6489560/deluge-pip_fail.txt)

I decided to upgrade the the deluge-pip from python 3.7 to 3.8 to see if that would fix the issue. 
I have upgraded the deluge-pip to reference all python3.8 packages
I have also upgraded the post_install.sh to reference python3.8

It now seems to play nicely.

please feel free to use the following commands to install youself

```
fetch https://raw.githubusercontent.com/Richardgriff/iocage-plugin-index/master/deluge-pip.json
iocage fetch -P deluge-pip.json -n deluge nat=1
```

feedback is welcome.

**Comment by jsegaert** [comment]
You are correct; The default version of Python switched from 3.7 to 3.8 recently causing breakage in several plugins.

I tested your changes and confirm that the plugin with your patch installed fine and let me download a torrent.  Can you submit a pull request with these changes?  Thanks!

**Comment by Richardgriff** [comment]
deluge-pip upgraded to python 3.8 #226 PR now approved issue can be closed
