### ISSUE TITLE
Jenkins Issue

### ISSUE THREAD

**Issue by Mcgregor381** [ix-plugin-hub/iocage-plugin-index#228]
both the LTS and  Standard version of Jenkins send me to the Nginx default error page.
and won't run using Nat 

Host Running Version:
TrueNAS-12.0-U3.1

Config used :
    all standard excluding providing a custom IP 192.168.*.**

is there a way to resolve this issue??

**Comment by fulder** [comment]
@Mcgregor381 the PR has just been merged, worked fine for me to install the non-LTS Jenkins version. Could you test again if it helped the issue you were having as well?

**Comment by Mcgregor381** [comment]
Never ment to close the issue was an accidental click on my mobile 

I am testing it now thank you for being so quick to take a look at it :D

**Comment by Mcgregor381** [comment]
so iv tryed intalling it on a jail with a static IP different to the host and without a static IP and it fails to install

it returns the following error in both cases :
Error: jenkins had a failure Exception: RuntimeError Message: pkg.FreeBSD.org could not be reached via DNS, check jenkins's network configuration Partial plugin destroyed.

if you want I can show you directly through a quick screen share if that would help

**Comment by Mcgregor381** [comment]
done A reboot of the host and a quick update seems like it's now working as intended :D thank you for the super-fast fix @fulder  
p.s iv more jail testing/ or testing in general ever needs to be done just mention me and ill help out if I can :)

**Comment by fulder** [comment]
@Mcgregor381 thank you for your testing and verification. I opened up a PR for the LTS version as well which got merged today as well here:  https://github.com/freenas/iocage-plugin-jenkins-lts/pull/1 as well as a cleanup/NAT portmapping fix PR in this repo here: 
 https://github.com/ix-plugin-hub/iocage-plugin-index/pull/229.

It looks like the CI tests are finally passing for these plugins now as well :) (after a small test fix/support PR: https://github.com/ix-plugin-hub/iocage-plugin-index/pull/231 and compared to latest master run or e.g. this old PR where they failed: https://github.com/ix-plugin-hub/iocage-plugin-index/pull/179), see e.g. run: https://cirrus-ci.com/task/5240738582626304
