### ISSUE TITLE
Jackett Doesn't Have Its Port Forwards Set By Default 

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#236]
On a new default plugin jail the Jackett admin interface is unreachable because the port forwards aren't set to 9117. Easy enough to fix if you're aware of what's wrong.

**Comment by fulder** [comment]
@jasker5183 thanks for this issue, I just created a PR for jackett nat properties in #237. Probably better to default to NAT settings with proper port forwarding in order to get it working for that kind of installation (changing it to DHCP should still work if wanted).
