### ISSUE TITLE
Sonarr and Radarr Default to Outdated Mono-5.10 

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#238]
Been trying to follow <https://www.truenas.com/community/threads/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.78871/page-8#post-623120> but wanted to test with another jail first but am having networking issues running different Radarr on different port (separate problem). I guess I could try snapshot and rollback if it fails, I'll try 6.8 first.

**Comment by jasker5183** [comment]
Both Sonarr and Radarr work with mono6.8.

**Comment by jasker5183** [comment]
I take that back it seems to break searching and syncing, had to rollback to mono510. Will try mono520 tomorrow.

**Comment by fulder** [comment]
@jasker5183 there was another issue about upgrading to mono here: https://github.com/ix-plugin-hub/iocage-plugin-index/issues/165. I still haven't really heard anything new when it comes to the 6.X mono packages for FreeBSD.

**Comment by jasker5183** [comment]
Upgraded Radarr's version of Mono to 5.20 and an update became available (3.2.2.5080) even though the package is version 3.0.2.4552. Radarr is running fine and the sync and search function is working. But now it's telling me "Please upgrade to the .NET Core version of Radarr, Mono versions will not be supported in the next release".

Sonarr's Mono 5.20 update went off without a hitch and the sync and search functions seem to be working.

**Comment by jasker5183** [comment]
The problem was mono6.8-6.8.0.123 if you use 6.8.0.105 everything works fine, there is a copy inside the Jackett jail at `/usr/local/migration/bin` or [here](https://www.truenas.com/community/threads/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.78871/page-4#post-573573) if you don't use Jackett. I'm also closing this as the plugins look like they default to mono6.8-6.8.0.123 now, this breaks the plugins but al least they aren't on a outdated version. Have a look at bug 276 (didn't want to link it) for the fix to that.
