### ISSUE TITLE
repo is currently blocked from cirrus CI - crypto miner prevention mechanisms was triggered

### ISSUE THREAD

**Issue by tprelog** [ix-plugin-hub/iocage-plugin-index#264]
I noticed on my last pull request that the cirrus check had been aborted.

![image](https://user-images.githubusercontent.com/35702532/133535082-bd8761c0-b4ca-4419-871c-d030e0c2d391.png)

So tried to trigger a re-run and ended up getting my own account suspended.

![image](https://user-images.githubusercontent.com/35702532/133535499-faa4af88-7442-41ec-83f9-e32561416817.png)

And I received the following reply after contacting cirrus support

> One of the crypto miner prevention mechanisms was triggered because it seems you have XMrig miner in your repository. 
>
> It doesn't seem you yourself is using it and mining crypto so I've unblocked your account. Is it possible to remove it?

**Comment by fulder** [comment]
I've noticed that during my latest `bazarr` PR as well (https://github.com/ix-plugin-hub/iocage-plugin-index/pull/260) nice you got a fast answer, I did try to email the support but didn't really get any reply regarding this repository.  

We could simply disable the `xmrig` task inside the `cirrus-ci` file if that's the one causing most troubles.

**Comment by fulder** [comment]
I've created a pull request (#265 ) commenting out the two plugin test tasks. Sent another email to Cirrus-CI support who have now unlocked this repository account as well.

**Comment by fulder** [comment]
Looks like the repository was unblocked but somehow got blocked once again after that :/ The `master` run after my PR got merged looks a bit weird where 2 tasks did run successful but the other two already got blocked: https://cirrus-ci.com/build/6649270443966464

And new PRs with new tasks are also blocked once again :( https://github.com/ix-plugin-hub/iocage-plugin-index/pull/266.

I've sent two mails to the cirrus-ci support about why this block is still happening (even though all crypto related plugins should now be disabled), awaiting an answer.

**Comment by leandroscardua** [comment]
Hi Fulder,

I think the repository was blocked again. :(

**Comment by leandroscardua** [comment]
The crypto thing is getting worse everywhere.
I hope the cirrus-ci can find a better way to block it :(

**Comment by fulder** [comment]
Got an answer the repository should be unblocked again. @leandroscardua could you try to add a dummy (e.g. empty) commit to your currently open branch/PR: #268 to verify if it works this time? :)

**Comment by leandroscardua** [comment]
Done.
Could you please check?

**Comment by fulder** [comment]
@leandroscardua looks like your fork was still in block mode but should work now again. Can you try once again and see if it works better?

**Comment by leandroscardua** [comment]
Ok, I just did.
let`s see if will unblock.
If you want, I can close that pull and open a new one.

**Comment by fulder** [comment]
Shouldn't be needed, it looks like it triggered the cirrus job correctly now (https://cirrus-ci.com/task/5590464905609216), thanks for you help regarding this issue.

**Comment by leandroscardua** [comment]
My pleasure, I`m glad to help. 
finally my pull request can be revised and approved if that is good :D
