### ISSUE TITLE
Chia Plugin Issue on CORE

### ISSUE THREAD

**Issue by sirdik** [ix-plugin-hub/iocage-plugin-index#270]
Hello, I'm getting an error on TrueNAS-12.0-U5.1 when trying to install the Chia Plugin. 

`
Error: Chia1 had a failure Exception: RuntimeError Message: Last 10 lines: warning: no previously-included files found matching 'codecov.yml' warning: no previously-included files found matching '.readthedocs.yml' warning: no previously-included files found matching 'dev-requirements.txt' warning: no previously-included files found matching 'rtd-requirements.txt' warning: no previously-included files found matching 'tox.ini' warning: no previously-included files matching '*' found under directory '.zuul.d' warning: no previously-included files matching '*' found under directory '.zuul.playbooks' Submodule 'mozilla-ca' (https://github.com/Chia-Network/mozilla-ca.git) registered for path 'mozilla-ca' Cloning into '/root/chia-blockchain/mozilla-ca'... ERROR: Could not find a version that satisfies the requirement clvm-rs==0.1.11 (from chia-blockchain) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10) ERROR: No matching distribution found for clvm-rs==0.1.11 /root/post_install.sh: line 63: ./venv/bin/chia: No such file or directory Partial plugin destroyed
`

**Comment by kmoore134** [comment]
Go ahead and re-test this please, we've updated the version of clvm-rs that is included now.

**Comment by sirdik** [comment]
Hello Kris, I'm still getting an error:
`Error: Chia1 had a failure Exception: RuntimeError Message: Last 10 lines: warning: no previously-included files found matching 'release.py' warning: no previously-included files found matching '.coveragerc' warning: no previously-included files found matching 'codecov.yml' warning: no previously-included files found matching '.readthedocs.yml' warning: no previously-included files found matching 'dev-requirements.txt' warning: no previously-included files found matching 'rtd-requirements.txt' warning: no previously-included files found matching 'tox.ini' warning: no previously-included files matching '*' found under directory '.zuul.d' warning: no previously-included files matching '*' found under directory '.zuul.playbooks' Submodule 'mozilla-ca' (https://github.com/Chia-Network/mozilla-ca.git) registered for path 'mozilla-ca' Cloning into '/root/chia-blockchain/mozilla-ca'... ERROR: Could not find a version that satisfies the requirement clvm-rs==0.1.11 (from chia-blockchain) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10) ERROR: No matching distribution found for clvm-rs==0.1.11 /root/post_install.sh: line 63: ./venv/bin/chia: No such file or directory Partial plugin destroyed
`

**Comment by kmoore134** [comment]
Ahh, found and fixed the issue now. Please give it another whirl.

**Comment by sirdik** [comment]
It is working now!
Thank you @kmoore134  for the quick fix!
