### ISSUE TITLE
Updating Jackett, Radarr, and Sonarr Jails Breaks Them

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#276]
Jackett, Radarr, and Sonarr all seem to update to the latest version just fine through their WebGUI's. But when updated through the Jails update process it seems to be break something to do with SSL, at least in Jackett and Radarr's case. Admittedly I have not tried Sonarr but I'm assuming the process will be the same. Jackett is unable to process search queries and Radarr is unable to contact the internet, it's unable to add anything new or even contact it's server for updates. 

Had to rollback snapshots to return them both to a running state. I did notice that the update upgraded mono from 5.20 to 6.8, no idea if that has anything to do with it since Jackett was already running that version. Attached is the log file from Radarr after the update, I did not grab one from Jackett. Let me know if you need anything else.

[radarr.txt](https://github.com/ix-plugin-hub/iocage-plugin-index/files/7339600/radarr.txt)

**Comment by fulder** [comment]
@jasker5183 good point about the evil :imp: `mono6.8-6.8.0.123` version. I was pretty puzzeled and stuck how this could be quickfixed with the updated and buggy version of mono for the jackett plugin I'm maintainer of.

I think I finally managed to add some (ugly?) patches/quickfixes for this to downgrade the mono version to the bundled one (you mentioned), remove the expired certificate from the FreeBSD list of trust and finally run the `cert-sync`. Looks like it works just fine after that and Jackett can now reach sites with `Let's Encrypt`  certificates again.

For more detail about the Jackett fixes see issue and comment in the Jackett repository here: https://github.com/fulder/iocage-plugin-jackett/issues/4#issuecomment-944931404

**Comment by jasker5183** [comment]
When I was looking about what to do about the errors I keep getting in Radarr about them no longer supporting Mono and using .NET in the future a Servarr wiki page linked me to [this page](https://github.com/Thefrank/freebsd-port-sooners). There are instructions on how to build a Radarr jail using the .NET version, was thinking on trying to upgrade my existing jail when I get brave enough. There is also an experimental version of Jackett 0.18.475, besides being an old version would this not be a better option going forward since Mono looks to not be maintained any longer?

I guess Mono is still being maintained, it's just getting small patches to a version that hasn't been updated in a year (come December).
