### ISSUE TITLE
12.2-RELEASE is approaching its End-of-Life date

### ISSUE THREAD

**Issue by tprelog** [ix-plugin-hub/iocage-plugin-index#284]
I saw this message updating the 12.2-RELEASE using `iocage fetch`

```
WARNING: FreeBSD 12.2-RELEASE is approaching its End-of-Life date.
It is strongly recommended that you upgrade to a newer
release within the next 1 month.
```

Past experience tells me, plugins start to fall apart when trying to use an EOL release.

Will there be a 12.3-RELEASE branch for plugins?

**Comment by kmoore134** [comment]
We are working towards a quick 13.0 release to try and sync with the EOL of 12.2.

**Comment by tprelog** [comment]
Hi @kmoore134, thanks for the reply.

Is it correct to assume that will only be available for the next version, TrueNAS CORE 13.0?

Some users won't want to install the next TrueNAS version right away. For user's user who aren't on the leading edge:
- Will it be possible to create a normal, non-plugin jail using the 12.3-RELEASE?
- If so, is there any way to convert a base (plugin) jail to a clone (non-plugin) jail?

I'm just trying to help give some plugin users an early heads-up - Thanks again for your time!

**Comment by kmoore134** [comment]
Yes, that would assume they are moving to a 13.0 Base rather quickly. Looping in @sonicaj if he has any information on if its possible to use 12.3-RELEASE on TrueNAS 12.0 - I'm not sure offhand.

**Comment by sonicaj** [comment]
@tprelog you should be able to consume 12.3-RELEASE without any issues on TrueNAS 12.0.

**Comment by tprelog** [comment]
Thanks again guys!

I got a CORE server fired up again (currently running SCALE) to test some plugins on the `12.3-RELEASE`

 **I've noticed something I think is strange. Can you please say if the following is normal?**

To explain briefly - Several of my plugins are Python applications that get installed inside a python virtualenv.  During installation, python compiles some additional modules or wheels. In all three jails I've created using the `12.3-RELEASE`, the python wheels are still being built for `freebsd_12_2_release_p11`

I created 3 jails: base, clone and thick

```
+------+----------------+------+---------+----------+------------------+---------------------+-----+----------+----------+
| JID  |      NAME      | BOOT |  STATE  |   TYPE   |     RELEASE      |         IP4         | IP6 | TEMPLATE | BASEJAIL |
+======+================+======+=========+==========+==================+=====================+=====+==========+==========+
+------+----------------+------+---------+----------+------------------+---------------------+-----+----------+----------+
| 1    | abasejail      | off  | up      | jail     | 12.3-RELEASE     | epair0b|10.10.1.194 | -   | -        | yes      |
+------+----------------+------+---------+----------+------------------+---------------------+-----+----------+----------+
| 2    | aclonejail     | off  | up      | jail     | 12.3-RELEASE     | epair0b|10.10.1.182 | -   | -        | no       |
+------+----------------+------+---------+----------+------------------+---------------------+-----+----------+----------+
| 3    | athickjail     | off  | up      | jail     | 12.3-RELEASE     | epair0b|10.10.1.106 | -   | -        | no       |
```

Here is an example from thick jail but results are the same in all 3 types

```
root@athickjail:~ # freebsd-version
12.3-RELEASE
```

But when installing application inside the virtualenv, wheels are built for `12.2-RELEASE`
```
Building wheels for collected packages: aiohttp, bcrypt, ciso8601, cryptography, python-slugify, pyyaml, voluptuous, yarl, cffi, frozenlist, MarkupSafe, multidict
  Building wheel for aiohttp (PEP 517) ... done
  Created wheel for aiohttp: filename=aiohttp-3.8.1-cp39-cp39-freebsd_12_2_release_p11_amd64.whl size=580620 sha256=21576aba30036d732e82f203977c78cf7fb513e05c8e69e900f9e0f0d515e4a6
  Stored in directory: /tmp/pip-ephem-wheel-cache-voc5tw3a/wheels/18/3d/16/11bf4b984ebad9a308297e1dd7ece9703314c8a4361f770e4f
  Building wheel for bcrypt (PEP 517) ... done
  Created wheel for bcrypt: filename=bcrypt-3.1.7-cp39-cp39-freebsd_12_2_release_p11_amd64.whl size=33935 sha256=e2ed9a252a6605d3083aa10e25e35ae8c972c20382d00b839963db8161079da2
  Stored in directory: /tmp/pip-ephem-wheel-cache-voc5tw3a/wheels/a2/df/9f/3e737db43b7e03632c1c23099d36e022c9fc5fb98e1b283fd2
  Building wheel for ciso8601 (PEP 517) ... done
  Created wheel for ciso8601: filename=ciso8601-2.2.0-cp39-cp39-freebsd_12_2_release_p11_amd64.whl size=14399 sha256=9bbf10e661ee779050c4dc91977eeb5076d2784b944b74f1e40073d2d7ec4026
  Stored in directory: /tmp/pip-ephem-wheel-cache-voc5tw3a/wheels/eb/ef/30/b91c5119b2581a9d66d18f827d53432f85417ffab180f3e5b8
  Building wheel for cryptography (PEP 517) ... |
```

And the application itself, still reports the OS version as `12.2-RELEASE-p11`

![image](https://user-images.githubusercontent.com/35702532/147771031-0836a416-694f-4f1f-b94c-3da0063fef87.png)

**Comment by sonicaj** [comment]
@tprelog when we use a jail with a different version then the host i.e 12.3/12.1 jail on 12.2 host, the userland bits change as per the desired jail version but the kernel version is still the same as the host which is why it reports it correctly. Normally/generally we use `freebsd-version` to see what it reports in the jail for freebsd version.
