### ISSUE TITLE
Unable to connect to Deluge WebUI using TrueNAS Core

### ISSUE THREAD

**Issue by Black-86156** [ix-plugin-hub/iocage-plugin-index#285]
I have tied to install Deluge multiple times from the TrueNAS Plugin repository, it installs successfully, however when I try to go to the plugin page i get a connection error, Firefox just quits, Chrome says connection refused, however I can install other plugins (Plex, Jacket) and get to their interfaces just fine.  

TrueNAS Version: 12.0-U7

From the Plug-in page:
IPv4 Address:

172.16.0.2/30
IPv6 Address:

N/A
Version:

N/A
Plugin:

deluge-pip
Release:

12.2-RELEASE-p11
Collection:

https://github.com/ix-plugin-hub/iocage-plugin-index.git

I should be connecting through the TrueNAS Host at 192.168.12.116:8112

I haven't changed anything additional, a fried is running a previous release for Deluge just fine and the permissions are build the same as far as I can tell.

What am I doing wrong here?

[Deluge Install Notes.txt](https://github.com/ix-plugin-hub/iocage-plugin-index/files/7796470/Deluge.Install.Notes.txt)

**Comment by jsegaert** [comment]
This should be fixed, also see jsegaert/iocage-plugin-deluge-pip#7
Please try again and confirm.

**Comment by Black-86156** [comment]
confirmed, worked like a champ.  ty!
