### ISSUE TITLE
Plugins Are Not Showing Up In TrueNAS WebGUI

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#295]
Just submitted a Prowlarr plugin and was wondering how long it took to post in the TrueNAS webGUI after the merge? I also notice a few other plugins are not showing up as well such as mariadb, guacamole, torrserver, etc. Those are just the ones I noticed but there are possibly more.

Could this just be me? If so how do I fix it?

EDIT: Just seems to be the last four submitted plugins.

**Comment by sonicaj** [comment]
@jasker5183 that is because 12.2-RELEASE has not been updated from master yet. We'll be updating it soon and those plugins should show nicely then.

**Comment by jasker5183** [comment]
Looks like an update was merged to the 12.2 repo about 14 days ago and the new plugins are showing up in the GUI not sure why this didn't auto close, closing.
