### ISSUE TITLE
chmod: /usr/local/prowlarr: No such file or directory

### ISSUE THREAD

**Issue by callaa3** [ix-plugin-hub/iocage-plugin-index#303]
@jasker5183 thanks for putting this together. Just installed it and I can access it Ok thus far. Just wanted to flag the post install chmod errors below incase this is an issue in some way.

Plugin installed successfully
Install Notes:
prowlarr_enable: -> YES
prowlarr_enable: -> YES
chmod: /usr/local/prowlarr: No such file or directory
Starting prowlarr.
chmod: /usr/local/prowlarr: No such file or directory
Admin Portal:
http://192.168.1.30:9696

**Comment by jasker5183** [comment]
I could change my artifact script to not chmod the directory but like all the other `arr`'s it's probably a good idea just in case. The reason you're getting that error is because the directory doesn't exist to apply the chmod to until after Prowlarr starts.

**Comment by callaa3** [comment]
OK, thanks for the response.

**Comment by callaa3** [comment]
OK, thanks for the response.
