### ISSUE TITLE
Update Community Plugin's to 13.1-RELEASE

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#316]
Now that TrueNAS CORE U1 is out and we are running proper 13.1 can we please upgrade our jails?

Thanks.

**Comment by Baenwort** [comment]
I've started for Calibre and Emby and I'm sure the other plug in people are working on theirs also. If you'd like to pitch in and test if there are any breaks I think we all appreciate help as we are volunteers

**Comment by Dime274** [comment]
Can we get unpackerr added as a community plug in

**Comment by jasker5183** [comment]
Closing as the plugin's were updated today.
