### ISSUE TITLE
Issues to Keep an Eye On

### ISSUE THREAD

**Issue by jasker5183** [ix-plugin-hub/iocage-plugin-index#326]
Just wanted to make a placeholder issue to keep track of things. ~~I should mention with today's update of the plugin's that openspeedtest-server is probably broken~~. Also that hoobs, ~~nexus-oss,~~ and torrserver have been broken since 12.3 and if these issues are not resolved they should probably be removed from the community plugins.

[Sonarr](https://github.com/freenas/iocage-plugin-sonarr/issues/1)  CLOSED
[SickChill](https://github.com/SickChill/SickChill/issues/8057) CLOSED
[Piwigo](https://github.com/AfroUSApl/iocage-plugin-piwigo/issues/6) - FIXED (see note below)
[Openspeedtest-server](https://github.com/openspeedtest/iocage-plugin-OpenSpeedTest-Server/issues/2) - FIXED
[Nexus-OSS](https://github.com/rebasing-xyz/iocage-nexus-oss/issues/27) - FIXED
[Torr_Server](https://github.com/filka96/iocage-plugin-TorrServer/issues/4) CLOSED
[Hoobs](https://github.com/rahul-r/iocage-plugin-hoobs/issues/1) CLOSED

Might also be time to clean up the issue tracker? There are issues here that go back to 11.3.

Piwigo - Follow post install notes, you still get a blank white screen, it will install but when you go back to admin portal it works.

**Comment by Baenwort** [comment]
If you see a Emby issue please ping me and I'll try to address it.

**Comment by AfroUSApl** [comment]
Piwigo seems to be working again with truenas 12 and updated PHP 7.4

**Comment by jasker5183** [comment]
Had it with the community plugins's so I'm closing all of these issues IX is removing the functionality in early 2025 anyways and if you already aren't using custom basejails you really should be.
