### ISSUE TITLE
Calibre-web plugin fails to load web interface after stopping and starting plugin

### ISSUE THREAD

**Issue by jonskoglund** [ix-plugin-hub/iocage-plugin-index#330]
Hi. I'm having issues with the Calibre Web plugin on TrueNAS-13.0-U2. After installing this plugin the web interface of Calibre loads  as it should. But somehow it stops running after stopping and starting the plugin. Have no idea how to get it up and running. Any ideas what to do to fix this issue?

**Comment by Baenwort** [comment]
try entering the jail shell and putting in the command:

`service calibre_web start`

then pressing enter

**Comment by jonskoglund** [comment]
Whoops!! Why didn't I think of that. Thank you so much. haha.
