### ISSUE TITLE
Transmission web UI becomes inaccessible after a while

### ISSUE THREAD

**Issue by Matiasgroen** [ix-plugin-hub/iocage-plugin-index#360]
I have installed the Transmission plugin with defaults settings and initially everything works fine, but after a while (a day or so) the web UI becomes inaccessible. Restarting the service doesn't work. I have to restart the entire jail for it to work again. Any idea what it could be?

**Comment by Baenwort** [comment]
Does the log file for either the server or the jail give any clues?

**Comment by Matiasgroen** [comment]
I have since reinstalled Transmission manually in a jail and I encountered the same issue as with the plugin. I gave that jail it's own IP address with DHCP instead of using NAT forwarding and that seems to have solved the it. Had the same problem with the Netdata dashboard.
