### ISSUE TITLE
Unifi Config Files

### ISSUE THREAD

**Issue by overkillthemighty** [ix-plugin-hub/iocage-plugin-index#37]
The unifi controllers are useless as they are configured. With a NAT config they need to have these ports passed through:
https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
the first two are the most important.
I do not see any other plugins with multiple ports behind NAT, so I am not sure how to format it. The other options are to change it to a vnet/dhcp so it has full control of its own ports (we could then use a reservation to set it's address) or (if possible) allow us to set a static address.

**Comment by kmoore134** [comment]
@sonicaj can you provide an example of how to do multiple ports in the JSON config?

**Comment by sonicaj** [comment]
@overkillthemighty the format for specifying multiple nat forwarding ports is to concatenate them with a `,`. Kindly see the following example:
```
    "properties": {
        "nat": 1,
        "nat_forwards": "tcp(8888:8888),tcp(9999:9999)"
    },
```

Please let me know if the above is unclear or there are issues setting it correctly. Thank you
