### ISSUE TITLE
Include Unifi Poller to unifi plugin

### ISSUE THREAD

**Issue by Ornias1993** [ix-plugin-hub/iocage-plugin-index#38]
With some work and pressure it seems Unifi Poller (which makes Unifi data available to other time-based database systems for logging), has been mostly done with creating a FreeBSD version.

As I already tested the basic setup on FreeNAS I can confirm this works on freenas as well and would be quite nice to get integrated into the plugin (maybe as an optional setting).

https://github.com/unifi-poller/unifi-poller/issues/170#issuecomment-581084134

**Comment by fulder** [comment]
A bit late answer but I tried to make a new fork of the unifi freemas plugin including the unifi-poller plugin which can be enabled/disabled using a new setting `unifi_poller_enable=<false|true>`. Note that this will just enable the plugin/service and it still needs to be configured for the wished settings using the `/usr/local/etc/unifi-poller/up.conf` (I do echo about this file when the `unifi_poller_enable` is set to `true`) 

@Ornias1993 if this feature is still wanted and when you get some time over you could try to install unifi plugin from my fork: https://github.com/fulder/iocage-plugin-unificontroller. And if it looks fine I can create a PR for the changes.

**Comment by Ornias1993** [comment]
Freenas plugins are not supposed to have config files that require the CLI.

Im running unifi + poller successfully using jailman for some time now :)
