### ISSUE TITLE
[Emby Server Stable] Missing pakages

### ISSUE THREAD

**Issue by zorglube** [ix-plugin-hub/iocage-plugin-index#384]
I juste add a look at the Emby BSD install man : https://emby.media/freebsd-server.html 

And it seems that the manifest : [emby-server-stable.json](https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/emby-server-stable.json) is missing some packages announced by Emby team. 

Missing packages are : `libexif libjxl libheif libimagequant openexr openjpeg orc pango tiff`

Am I right ?

**Comment by zorglube** [comment]
Also I created a PR : https://github.com/ix-plugin-hub/iocage-plugin-index/pull/385

**Comment by tprelog** [comment]
Those packages are already listed as dependencies, which means they get installed automagically when installing Emby

https://www.freshports.org/multimedia/emby-server/

There's no need to explicitly install these separately

**Comment by zorglube** [comment]
Okay, so I let you close the Issue and PR. 

By the way, my TrueNAS can't download `ImageMagick6` while installing Emby, do you have any idea about why ?

**Comment by zorglube** [comment]
> Okay, so I let you close the Issue and PR. 
> 
> By the way, my TrueNAS can't download `ImageMagick6` while installing Emby, do you have any idea about why ? 

Problem solved, probably a cache issue.
