### ISSUE TITLE
Version is NA

### ISSUE THREAD

**Issue by tprelog** [ix-plugin-hub/iocage-plugin-index#47]
I have a couple questions about setting the version numbers.

When I have pointed out to some people about the plugins I have submitted, the first response is always 
> It says version NA

![image](https://user-images.githubusercontent.com/35702532/74107840-11fdec80-4b42-11ea-8d41-87af8144ac07.png)

So I have two questions

Is this Version number supposed to be the "plugin versions" or the "application version"?
_I'm hoping this is supposed to be the plugin version._

How do I set the version number that appears when browsing the plugins?

Thanks

**Comment by sonicaj** [comment]
Hi @tprelog. So the `version` here is supposed to come from the primary pkg of the plugin installed. Please refer to `primary_pkg` attribute in INDEX for plugins, that defines the pkg we should use to determine the version of the plugin. For this plugin specifically, it's set to `null` which is why we don't show any version for it.

**Comment by tprelog** [comment]
@sonicaj, Thank you for explaining. I've kinda figured so much since I opened this issue. At least with the Mosquitto plugin, I have set the `primary_pkg` but it only shows the `version` after it's been installed.

![image](https://user-images.githubusercontent.com/35702532/78795174-b05fd000-7982-11ea-90b7-2d56c645ff5e.png)

---

> For this plugin specifically, it's set to `null` which is why we don't show any version for it.

This plugin is a tough example. Home Assistant Core (HA) is a Python application that is installed using using `pip`. This plugin will always install whatever version is the current stable release.

**Comment by sonicaj** [comment]
@tprelog so this issue has been addressed in 12 nightlies and will be available in 11.3 U3. Rest assured, it's only cosmetic and does not affect the installation of the plugin. ( All plugins having "ABI" in their packagesite will show this issue in U2 just in case you are curious )

**Comment by tprelog** [comment]
I'm not so much concerned myself, I was more surprised how much feedback about it from others.

In any case, I can now provide an answer when it's brought up :+1: 

Thank you for time explaining @sonicaj

**Comment by sonicaj** [comment]
Thank you for bringing it to our attention @tprelog and no problem
