### ISSUE TITLE
gitea can't use ssh

### ISSUE THREAD

**Issue by 3038922** [ix-plugin-hub/iocage-plugin-index#72]
freenas --version : FreeNAS-11.3-U2.1
jails --version : 11.3-RELEASE-p8
app.ini
```
START_SSH_SERVER = true
```
netstat -an
prot 22 is not LISTEN
```
root@gitea:/usr/local/etc/gitea/conf # netstat -an
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp46      0      0 *.3000                 *.*                    LISTEN
tcp4       0      0 127.0.0.1.5432         127.0.0.1.14660        ESTABLISHED
tcp4       0      0 127.0.0.1.14660        127.0.0.1.5432         ESTABLISHED
tcp4       0      0 127.0.0.1.5432         127.0.0.1.55364        ESTABLISHED
tcp4       0      0 127.0.0.1.55364        127.0.0.1.5432         ESTABLISHED
tcp4       0      0 *.5432                 *.*                    LISTEN
tcp6       0      0 *.5432                 *.*                    LISTEN
udp6       0      0 ::1.22268              ::1.22268
icm6       0      0 *.*                    *.*
Active UNIX domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn    Refs          Nextref Addr
fffff801c94f9690 stream      0      0 fffff80364b1fb10                0       0                0 /tmp/.s.PGSQL.5432
fffff801c7698690 dgram       0      0                0 fffff801c7698a50       0 fffff801c7698c30
fffff801c7698c30 dgram       0      0                0 fffff801c7698a50       0 fffff8003d81b4b0
fffff8003d81b4b0 dgram       0      0                0 fffff801c7698a50       0 fffff801c7698960
```

**Comment by fulder** [comment]
After some debugging of gitea I found out the `[server]` block in the `app.ini` seems to have missing 

```
START_SSH_SERVER = true
```
See [gitea docs](https://docs.gitea.io/en-us/config-cheat-sheet/#server-server)

Also as the service is started using the `git` user (inside a deamon) this user is not allowed to open up connections on the standard port 22.

Changing the port to something higher (for example 2222) make it work for me and I could clone a test repo through SSH. This is just an ugly quickfix and should probably be fixed properly by the gitea plugin owner. Just wanted to share my finding.

**Comment by 3038922** [comment]
> After some debugging of the gitea plugin I found out that the service is started using the `git` user (inside a deamon), and I think this user is not allowed to open up connections on the standard port 22.
> 
> Changing the port to something higher (for example 2222) make it work for me and I could clone a test repo through SSH. This is just an ugly quickfix and should probably be fixed properly by the gitea plugin owner. Just wanted to share my finding.
> 
> The `START_SSH_SERVER` `app.ini` property is also missing from the config after a fresh install. Got a bit confused why there were no logs about SSH at all at first, maybe it would be a good idea to add it and set it to the default `false` value as well?

```
 ⚡ root@gitea  /usr/local/git/.ssh  pwd
/usr/local/git/.ssh
 ⚡ root@gitea  /usr/local/git/.ssh  ls -l
total 8
-rw-------  1 git  git  744 Apr 25 02:26 authorized_keys
```
I add public-key in the web background. It will not be added with it.
what is the user name of the web backend?

**Comment by 3038922** [comment]
add git to root group....it can be used
