### ISSUE TITLE
"madsonic-standalone" package missing from pkg.cdn.trueos.org repo

### ISSUE THREAD

**Issue by jsegaert** [ix-plugin-hub/iocage-plugin-index#74]
I just noted a report that the madsonic plugin is broken.  

It seems that the `madsonic-standalone` pkg is missing from the TrueOS repository at http://pkg.cdn.trueos.org/iocage/11.3-RELEASE/All/ but there is a `subsonic-standalone` pkg.

Did this package fail to build?  Is that repo still maintained?

**Comment by fulder** [comment]
You're right it does seem gone and broken. It doesn't seem to exist in `pkg.FreeBSD.org` repo either. 

Isn't `subsonic` a bit different than `madsonic`? Maybe a new plugin could be created for it? 

After a quick research I couldn't find any working `madsonic` package for FreeBSD, another possible solution is to just install it from the tar.gz in a more manual manner: https://www.madsonic.org/pages/installation.jsp#standalone but this should probably be done by the plugin maintainer.

**Comment by jsegaert** [comment]
Thanks for the feedback.  The FreeBSD repo does have a [madsonic-jetty](https://www.freshports.org/www/madsonic/) pkg, but just simply swapping `madsonic-standalone` to `madsonic-jetty` and pointing madsonic.json to the FreeNAS repo didn't work - I tried.

MadSonic, AirSonic, LibreSonic all seem to be open source forks from Subsonic.

**Comment by fulder** [comment]
I saw the `madsonic-jetty` pkg as well, thought first it was just some jetty server for the madsonic. But it actually looks like it includes both jetty and madsonic.

While switching to this "new" package you should also edit the service name from `madsonic` to `jetty`. I've managed to get it working that way and (after some tweaks in the jettyctl not being totaly compatible with python3, see [this issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242014)) and although the service `rc.d` script doesn't seem to be completely working (it logs warnings and I cannot use it properly to stop or get status of the running server) I managed to get both jetty (at localhost:8080) and madsonic (at localhost:8080/madsonic/) UIs to work properly.

That package seems a bit outdated as well as it runs Madsonic `6.2.9040` and the newest versions seems to be `7.0.10360`.

Checking the official page for Madsonic it looks like it should be installed using ports: https://beta.madsonic.org/pages/installation.jsp#freebsd but this method doesn't work either as it seems to be missing from ports as well.

**Comment by fulder** [comment]
I've created a fork and PR for the madsonic plugin for a version of it installed from the `tar.gz` package. Have tested a bit and it looks like it works properly and madsonic is again wokring at the same URL: `http://localhost:4040`

**Comment by jsegaert** [comment]
Nice work!  :+1: 

The new version from master installs correctly.  Once logged on to the web UI, I set up a few media folders, it scanned them fine and the tracks played correctly.  Thank you; I'll close this issue.
